### ISSUE TITLE
Please upload the Test for Inverse Problem code

### ISSUE THREAD

**Issue by fbl1991** [pentilm/Hybrid-PINN#1]
Dear Doctor Fang,

Would you please upload the test for inverse problem code? 
I'm doing research on the inverse heat problem using PINN. But the solution cannot converge to the right answer. When I encounter on your work, I realize that maybe your hybrid pinn method would solve my problem. The Test for inverse problem in your paper is much similar to my problem. Would you help me to upload your code? Cause your method is of high technique skills, which is hard for me to construct.

**Comment by pentilm** [comment]
The code for the inverse problem has been uploaded.
